= Conjure Sourcery

 * 10/04/2020 - This repo has served it's purpose and has been moved into the develop branch of the main https://github.com/Olical/conjure[Conjure] repository.
____
As they say in Discworld, we are trying to unravel the Mighty Infinite using a language which was designed to tell one another where the fresh fruit was.

— Terry Pratchett in Sourcery 
____

An experimental reimplementation of https://github.com/Olical/conjure[Conjure] in Lua via https://github.com/bakpakin/Fennel[Fennel]. This is mostly made possible by my precursor project to this one, https://github.com/Olical/aniseed[Aniseed]. It's a toolkit that aids development of Neovim plugins and configuration through Fennel.

If this experiment is a success it'll eventually replace the main repository as the default Conjure implementation. I'm planning on carrying over a lot of the best behaviors and features while making it smoother, faster and easier to use.

I'm also considering supporting other Lisps such as Scheme, Racket and Fennel. I think the model of selecting forms and working with results in alog buffer is universal, the thing that changes is how evaluations are performed and wrapped. Food for thought!

== Unlicenced

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
